name: Build System Images

on:
  schedule:
    - cron: '36 3 * * *'
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-system-image:

    runs-on: ubuntu-latest
    timeout-minutes: 2880
    permissions:
      contents: read
      packages: write

    env:
      SKIFF_CONFIG: pi/4x64,apps/satellite
      SKIFF_WORKPLACE: pi4
      PI_IMAGE: /tmp/rhasspy-satellite-pi4.img

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache build cache and downloads
        uses: actions/cache@v2
        env:
          cache-name: cache-buildroot
        with:
          path: ~/br-cache/
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Clear caches if necessary
        run: |
          # necessary to save space
          if [ ! -f ~/br-cache/ccache-v8 ]; then
            echo "Clearing old compiler cache..."
            rm -rf ~/br-cache/ccache* || true
            mkdir -p ~/br-cache/ccache
            touch ~/br-cache/ccache-v8
          fi
          if [ ! -f ~/br-cache/dl-v8 ]; then
            echo "Clearing old downloads cache..."
            rm -rf ~/br-cache/dl* || true
            mkdir -p ~/br-cache/dl
            touch ~/br-cache/dl-v8
          fi

      - name: Install docker w/buildkit
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Install everything for Buildroot/SkiffOS
        run: > 
          sudo apt update && 
          sudo apt install -y build-essential
          git gcc wget curl musl-dev file
          perl python rsync bc patch unzip cpio
          pigz

      - name: Build Pi4 Image
        run: |
          export TERM=xterm
          export BR2_CCACHE_DIR=${HOME}/br-cache/ccache
          export BR2_DL_DIR=${HOME}/br-cache/dl
          make configure && make compile

      - name: Make SD Image
        run: make cmd/pi/common/buildimage

      - name: Compress SD Image
        run: pigz -9 $PI_IMAGE

      - name: Upload!
        uses: actions/upload-artifact@v2
        with:
          name: rhasspy-satellites
          path: /tmp
