name: Build System Images

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      SKIFF_CONFIG: pi/4x64,apps/satellite
      SKIFF_WORKSPACE: pi4
      PI_IMAGE: /tmp/rhasspy-satellite-pi4.img

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install docker w/buildkit
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Install everything for Buildroot/SkiffOS
        run: > 
          sudo apt update && 
          sudo apt install -y build-essential
          git gcc wget curl musl-dev file
          perl python rsync bc patch unzip cpio
          pigz

      - name: Build Pi4 Image
        run: make configure && make compile

      - name: Make SD Image
        run: make cmd/pi/common/buildimage

      - name: Compress SD Image
        run: pigz -9 $PI_IMAGE

      - name: Upload!
        uses: actions/upload-artifact@v2
        with:
          name: rhasspy-satellites
          path: /tmp
