name: Build System Images

on:
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]

jobs:
  build-system-image:

    runs-on: [self-hosted, pi4]
    timeout-minutes: 2880
    permissions:
      contents: read
      packages: write

    env:
      SKIFF_CONFIG: pi/4x64,apps/satellite
      SKIFF_WORKPLACE: pi4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Buildroot compile cache + dls
        uses: actions/cache@v2
        with:
          path: ~/br-cache
          key: ${{ runner.os }}-buildroot-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildroot-

      - name: Build Pi4 Image
        run: |
          export TERM=xterm
          export BR2_CCACHE_DIR=${HOME}/br-cache/ccache
          export BR2_DL_DIR=${HOME}/br-cache/dl
          make configure && make compile

      - name: Make SD Image
        run: sudo TERM=xterm PI_IMAGE=/tmp/rhasspy-satellite-pi4.img make cmd/apps/satellite/buildimage

      - name: Gzip the SD Image
        run: pigz -9 -f -k /tmp/rhasspy-satellite-pi4.img

      - name: Upload!
        uses: actions/upload-artifact@v2
        with:
          name: rhasspy-satellite-pi4.img
          path: /tmp/rhasspy-satellite-pi4.img.gz
